# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crowd_rails}
  s.version = "0.5.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Stefan Wille"]
  s.date = %q{2010-07-26}
  s.description = %q{Single Sign On for Atlassian Crowd 2.0}
  s.email = %q{post @nospam@ stefanwille.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/crowd_rails.rb",
     "test/helper.rb",
     "test/test_crowd_rails.rb"
  ]
  s.homepage = %q{http://github.com/stefanwille/crowd_rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Single Sign On for Atlassian Crowd 2.0}
  s.test_files = [
    "test/helper.rb",
     "test/test_crowd_rails.rb",
     "test/test_crowd_rails_orig.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<crowd-stefanwille>, ["= 0.5.10"])
    else
      s.add_dependency(%q<crowd-stefanwille>, ["= 0.5.10"])
    end
  else
    s.add_dependency(%q<crowd-stefanwille>, ["= 0.5.10"])
  end
end

